### ISSUE TITLE
Swal is not working

### ISSUE THREAD

**Issue by sibelius** [lanetix/react-swal#6]
The swal doesn't appear as a modal, this is appearing in the bottom of my page

![sweetalert](https://cloud.githubusercontent.com/assets/2005841/14330296/550d6192-fc16-11e5-931b-ccdeb73b1581.png)

**Comment by bnsd55** [comment]
Hey,
you have to call CSS file from your index.html in node_modules/sweetalert/dist

**Comment by sibelius** [comment]
I've imported the css file from the entry file using webpack 

I think this info should be on README.md
